name: Build Push Image

on:
  push:
    branches:
      - main
      - test
    tags:
      - '*'

jobs:

  build-push:
    runs-on: [gpu]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Define image tags
        run: |
          echo "IMAGE_NAME_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "GHCR_TAG=ghcr.io/${IMAGE_NAME_LOWER}:develop" >> $GITHUB_ENV
          echo "DOCKERHUB_TAG=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/$(basename $IMAGE_NAME_LOWER):develop" >> $GITHUB_ENV

      - name: Build and push to registries
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ env.GHCR_TAG }}
            ${{ env.DOCKERHUB_TAG }}
          target: develop
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
