name: Build Push Image

on:
  push:
    branches:
      - main
      - test
    tags:
      - '*'

jobs:

  build-push:
    runs-on: [gpu]

    strategy:
      matrix:
        target: [release, develop]

    steps:
      - name: Define environment variables
        run: |
          echo IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
          echo IMAGE_TAG=$(echo ${{ matrix.target }}) >> $GITHUB_ENV
          if [ "${{ matrix.target }}" = "release" ]; then
            echo IMAGE_TAG=latest >> $GITHUB_ENV
          fi

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to registries
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
           ghcr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
           docker.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          target: ${{ matrix.target }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

  build-push-cleanup:
    runs-on: ubuntu-latest
    needs: build-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: .github/workflows/delete_untagged.py ${{ secrets.GITHUB_TOKEN}}
