name: Build Push Image

on:
  push:
    branches:
      - main
      - test
    tags:
      - '*'

permissions:
  contents: read
  packages: write

jobs:

  build-push:
    runs-on: [gpu]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Define image tags
        run: |
          echo "IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push to registries
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
           ghcr.io/${{ env.IMAGE_NAME }}:develop
           docker.io/${{ env.IMAGE_NAME }}:develop
          target: develop
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
